<?php

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataType;

class CompaniesBreadRowAdded extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
        try {
            \DB::beginTransaction();

            $dataType = DataType::where('name', 'companies')->first();

            \DB::table('data_rows')->insert(array (
                0 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'id',
                    'type' => 'text',
                    'display_name' => 'Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 1,
                ),
                1 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'company',
                    'type' => 'text',
                    'display_name' => 'Company',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 2,
                ),
                2 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'owner',
                    'type' => 'text',
                    'display_name' => 'Owner',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 3,
                ),
                3 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'email',
                    'type' => 'text',
                    'display_name' => 'Email',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 4,
                ),
                4 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'address',
                    'type' => 'text',
                    'display_name' => 'Address',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 5,
                ),
                5 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'zipcode',
                    'type' => 'number',
                    'display_name' => 'Zipcode',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 6,
                ),
                6 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'phone',
                    'type' => 'number',
                    'display_name' => 'Phone',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 7,
                ),
                7 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'name_notify',
                    'type' => 'text',
                    'display_name' => 'Name Notify',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 8,
                ),
                8 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_bd_transfers',
                    'type' => 'number',
                    'display_name' => 'Amount Bd Transfers',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 9,
                ),
                9 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_bd_exchanges',
                    'type' => 'number',
                    'display_name' => 'Amount Bd Exchanges',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 10,
                ),
                10 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_to_require_id',
                    'type' => 'number',
                    'display_name' => 'Amount To Require Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 11,
                ),
                11 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'days_to_require_id',
                    'type' => 'number',
                    'display_name' => 'Days To Require Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 12,
                ),
                12 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'days_check_to_authorization',
                    'type' => 'number',
                    'display_name' => 'Days Check To Authorization',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 13,
                ),
                13 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_require_adicional_id',
                    'type' => 'number',
                    'display_name' => 'Amount Require Adicional Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 14,
                ),
                14 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'adicional_ids',
                    'type' => 'number',
                    'display_name' => 'Adicional Ids',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 15,
                ),
                15 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_to_notify',
                    'type' => 'number',
                    'display_name' => 'Amount To Notify',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 16,
                ),
                16 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'days_to_notify',
                    'type' => 'number',
                    'display_name' => 'Days To Notify',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 17,
                ),
                17 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'limit_by_day_transfers',
                    'type' => 'number',
                    'display_name' => 'Limit By Day Transfers',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 18,
                ),
                18 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'limit_by_day_exchanges',
                    'type' => 'number',
                    'display_name' => 'Limit By Day Exchanges',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 19,
                ),
                19 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'times_subsidiares',
                    'type' => 'number',
                    'display_name' => 'Times Subsidiares',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 20,
                ),
                20 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_subsidiaries',
                    'type' => 'number',
                    'display_name' => 'Amount Subsidiaries',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 21,
                ),
                21 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'days_subsidiaries',
                    'type' => 'number',
                    'display_name' => 'Days Subsidiaries',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 22,
                ),
                22 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_first_time_transfers',
                    'type' => 'number',
                    'display_name' => 'Amount First Time Transfers',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 23,
                ),
                23 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_first_time_exchanges',
                    'type' => 'number',
                    'display_name' => 'Amount First Time Exchanges',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 24,
                ),
                24 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_requiere_income',
                    'type' => 'number',
                    'display_name' => 'Amount Requiere Income',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 25,
                ),
                25 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'providers_transfers',
                    'type' => 'number',
                    'display_name' => 'Providers Transfers',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 26,
                ),
                26 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'providers_exchanges',
                    'type' => 'number',
                    'display_name' => 'Providers Exchanges',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 27,
                ),
                27 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'days_providers_exchanges',
                    'type' => 'number',
                    'display_name' => 'Days Providers Exchanges',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 28,
                ),
                28 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'days_providers_transfers',
                    'type' => 'number',
                    'display_name' => 'Days Providers Transfers',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 29,
                ),
                29 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'max_subidiaries',
                    'type' => 'number',
                    'display_name' => 'Max Subidiaries',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 30,
                ),
                30 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'logo',
                    'type' => 'image',
                    'display_name' => 'Logo',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 31,
                ),
                31 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'active',
                    'type' => 'checkbox',
                    'display_name' => 'Active',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 32,
                ),
                32 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'process_open',
                    'type' => 'number',
                    'display_name' => 'Process Open',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 33,
                ),
                33 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'process_close',
                    'type' => 'number',
                    'display_name' => 'Process Close',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 34,
                ),
                34 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'tx_subsidiary',
                    'type' => 'number',
                    'display_name' => 'Tx Subsidiary',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 35,
                ),
                35 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'tx_safe',
                    'type' => 'number',
                    'display_name' => 'Tx Safe',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 36,
                ),
                36 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'tx_register',
                    'type' => 'number',
                    'display_name' => 'Tx Register',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 37,
                ),
                37 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'tx_petty_cash',
                    'type' => 'number',
                    'display_name' => 'Tx Petty Cash',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 38,
                ),
                38 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'rx_subsidiary',
                    'type' => 'number',
                    'display_name' => 'Rx Subsidiary',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 39,
                ),
                39 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'rx_safe',
                    'type' => 'number',
                    'display_name' => 'Rx Safe',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 40,
                ),
                40 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'rx_register',
                    'type' => 'number',
                    'display_name' => 'Rx Register',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 41,
                ),
                41 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'rx_petty_cash',
                    'type' => 'number',
                    'display_name' => 'Rx Petty Cash',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 42,
                ),
                42 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'tx_express',
                    'type' => 'number',
                    'display_name' => 'Tx Express',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 43,
                ),
                43 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'ch_request',
                    'type' => 'number',
                    'display_name' => 'Ch Request',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 44,
                ),
                44 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'ch_accept',
                    'type' => 'number',
                    'display_name' => 'Ch Accept',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 45,
                ),
                45 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'ch_change',
                    'type' => 'number',
                    'display_name' => 'Ch Change',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 46,
                ),
                46 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'ch_receive',
                    'type' => 'number',
                    'display_name' => 'Ch Receive',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 47,
                ),
                47 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'service_id_payments',
                    'type' => 'text',
                    'display_name' => 'Service Id Payments',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 48,
                ),
                48 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'service_id_diference',
                    'type' => 'text',
                    'display_name' => 'Service Id Diference',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 49,
                ),
                49 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'copies_rate',
                    'type' => 'number',
                    'display_name' => 'Copies Rate',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 50,
                ),
                50 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'fax_nat_first_page_rate',
                    'type' => 'number',
                    'display_name' => 'Fax Nat First Page Rate',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 51,
                ),
                51 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'fax_nat_extra_page_rate',
                    'type' => 'number',
                    'display_name' => 'Fax Nat Extra Page Rate',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 52,
                ),
                52 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'fax_int_first_page_rate',
                    'type' => 'number',
                    'display_name' => 'Fax Int First Page Rate',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 53,
                ),
                53 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'fax_int_extra_page_rate',
                    'type' => 'number',
                    'display_name' => 'Fax Int Extra Page Rate',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 54,
                ),
                54 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_max_by_mo',
                    'type' => 'number',
                    'display_name' => 'Amount Max By Mo',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 55,
                ),
                55 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'amount_to_req_serial_mo',
                    'type' => 'number',
                    'display_name' => 'Amount To Req Serial Mo',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 56,
                ),
                56 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'expire_at',
                    'type' => 'timestamp',
                    'display_name' => 'Expire At',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 57,
                ),
                57 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 58,
                ),
                58 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 59,
                ),
            ));
        } catch(Exception $e) {
            throw new Exception('exception occur ' . $e);

            \DB::rollBack();
        }

        \DB::commit();
    }
}

